### ISSUE TITLE
Integrate from stenciljs app doesn't work like a normal stenciljs component

### ISSUE THREAD

**Issue by numerized** [fluster/web-social-share#38] opened 2020-08-18 16:03 UTC
Hi there, thanks for this cool component,

Unfortunately it doesn't work if integrated from within a pure stenciljs app.

It gives: 

```
TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 1
Declaration or statement expected.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 13
';' expected.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 8
Cannot find name 'type'.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 14
Cannot find name 'Components'.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 14
Left side of comma operator is unused and has no side effects.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 26
Cannot find name 'JSX'.
~dev-server:7 TypeScript ./node_modules\web-social-share\dist\types\interface.d.ts, line 1, column 31
Cannot find name 'from'.
``` 

I simply import the component with :

```import 'web-social-share'```

**Comment by peterpeterparker** [comment] 2020-08-18 16:05
I mostly used it in pure stenciljs app ;)

How do you import the component?

Here's how  I do it: https://github.com/deckgo/deckdeckgo/blob/f3ebcdfd45570452cdfc769765c6ccd8ea9fcaf5/studio/src/app/components/core/app-share-deck/app-share-deck.tsx

**Comment by peterpeterparker** [comment] 2020-08-18 16:06
Which version of the component are you using?

**Comment by numerized** [comment] 2020-08-18 17:11
the one from 
`$ npm install web-social-share`

(Thanks for flash gordon reply)

**Comment by peterpeterparker** [comment] 2020-08-18 17:15
`v6.4.1` then?

and stencil version? should not conflict with but just in case.

I tested in our app with  all last version and I was not able to reproduce your issue.

your repo  is open source? can I have a look/try?

**Comment by numerized** [comment] 2020-08-18 17:18
not open source, just if you confirm that my simple import integration is ok I'll try my end and update you what I find

**Comment by peterpeterparker** [comment] 2020-08-18 17:21
yep it is, like I said above, I do exactly the same `import` in our stencil  app

you can check the code there: https://github.com/deckgo/deckdeckgo/blob/f3ebcdfd45570452cdfc769765c6ccd8ea9fcaf5/studio/src/app/components/core/app-share-deck/app-share-deck.tsx

keep me posted!

**Comment by peterpeterparker** [comment] 2021-01-24 12:25
I'll close this issue since it wasn't  active for months. If you still face the issue, ping me, happy to reopen the question.

**Closed as completed by peterpeterparker** 2021-01-24 12:25 UTC
Labels: question
